baseURL = "https://filippo82.github.io/softwareunderground/" # https://gohugo.io/hosting-and-deployment/hosting-on-github/
publishDir = "docs" # see https://gohugo.io/hosting-and-deployment/hosting-on-github/
languageCode = "en-us"
title = "Software Underground"
theme = "kube_swung"
description = "The Software Underground is a grass-roots community of subsurface professionals - academic and applied geologists, geophysicists, resource engineers, and others - who write code and use computers in their work. Welcome!"
Paginate = 4
[Params]
RSSLink = "/index.xml"
author = "Software Underground" # add your company name
github = "softwareunderground" # add your github profile name
twitter = "" # add your twitter profile
email = "myemail@myaddress.xxx"

[[menu.main]]
name = "Doc"
weight = -100
url = "/docs/"
[[menu.main]]
name = "Projects"
weight = -100
url = "/projects/"
[[menu.main]]
name = "Blog"
weight = -100
url = "/blog/"
[[menu.main]]
name = "Faq"
weight = -100
url = "/faq/"
