baseURL = "https://filippo82.github.io/softwareunderground/" # https://gohugo.io/hosting-and-deployment/hosting-on-github/
publishDir = "docs" # see https://gohugo.io/hosting-and-deployment/hosting-on-github/
languageCode = "en-us"
title = "Software Underground"
theme = "kube_swung_v2"
description = "The Software Underground is a grass-roots community of subsurface professionals - academic and applied geologists, geophysicists, resource engineers, and others - who write code and use computers in their work. Welcome!"
Paginate = 4

#staticDir = ["images"]

pygmentsStyle= "monokailight"

[Params]
RSSLink = "/index.xml"
author = "Software Underground" # add your company name
github = "softwareunderground" # add your github profile name
twitter = "" # add your twitter profile
email = "myemail@myaddress.xxx"

# Choose weights to order the menus
[[menu.main]]
name = "Cookbook"
weight = -160
url = "/cookbook/"
[[menu.main]]
name = "Projects"
weight = -180
url = "/projects/"
[[menu.main]]
name = "Gallery"
weight = -170
url = "/gallery/"
[[menu.main]]
name = "Blog"
weight = -190
url = "/blog/"
[[menu.main]]
name = "Data catalogue"
weight = -150
url = "/data/"
[[menu.main]]
name = "Resources"
weight = -150
url = "/resources"
